# Generated by Django 5.0.6 on 2024-05-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baatein', '0002_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='talk_images/'),
        ),
    ]
