name: Test Deployment with GitHub Actions

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  test-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      
      - name: Create folder and add a text file on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "\
          mkdir -p ~/test-deployment && \
          echo 'This is a test file created on $(date)' > ~/test-deployment/testfile.txt"
